spec = [
    ("DELIM", r'\(|\)|\.|\,|\{|\}|\;'),
    ('NUM',  r'\d+(\.\d+)?'),
    ('OP_ADD', r'\+'),
    ('OP_SUB', r'\-'),
    ('OP_MULT', r'\*'),
    ('OP_DIV', r'\/'),
    ('OP_EXP', r'\^'),
    ('OP_GTE', r'>='),
    ('OP_STE', r'<='),
    ('OP_E', r'=='),
    ('OP_D', r'!='),
    ('OP_GT', r'>'),
    ('OP_ST', r'<'),
    ('CM_IF', r'if'),
    ('CM_ELSE', r'else'),
    ('CM_WHILE', r'while'),
    ('CM_VAR', r'var'),
    ('TYPE_INT', r'int'),
    ('TYPE_REAL', r'real'),
    ('CM_ATRIB', r'='),
    ('ID', r'[A-Z|a-z|]([A-Z|a-z|0-9]+)?'),
    ('LETTERS', r'[A-Za-z]+'),
    ('SKIP', r'[ \n\t\r]'),
]